
const ACTIVIDADES = [
  { id: 1, deporte: 'futbol',  titulo: 'Fútbol 7 en Miraflores',        dia: 'viernes',   num: 22, hora: '19:00', lugar: 'Complejo Miraflores',   distrito: 'Miraflores', cupos: 5,  total: 14, nivel: 'intermedio',   estado: 'disponible' },
  { id: 2, deporte: 'voley',   titulo: 'Vóley playa en Barranco',       dia: 'sabado',    num: 23, hora: '10:00', lugar: 'Playa Barranco',        distrito: 'Barranco',   cupos: 0,  total: 12, nivel: 'principiante', estado: 'llenos' },
  { id: 3, deporte: 'basquet', titulo: 'Básquet en San Miguel',         dia: 'sabado',    num: 23, hora: '16:00', lugar: 'Sede UPC San Miguel',   distrito: 'San Miguel', cupos: 3,  total: 10, nivel: 'intermedio',   estado: 'disponible' },
  { id: 4, deporte: 'tenis',   titulo: 'Dobles de tenis en San Isidro', dia: 'miercoles', num: 27, hora: '18:30', lugar: 'Club San Isidro',       distrito: 'San Isidro', cupos: 1,  total: 4,  nivel: 'avanzado',     estado: 'espera' },
  { id: 5, deporte: 'running', titulo: 'Trote grupal en Surco',         dia: 'domingo',   num: 24, hora: '06:00', lugar: 'Parque de la Amistad',  distrito: 'Surco',      cupos: 9,  total: 20, nivel: 'libre',        estado: 'disponible' },
  { id: 6, deporte: 'futbol',  titulo: 'Fútbol 5 en Los Olivos',        dia: 'jueves',    num: 28, hora: '20:00', lugar: 'Complejo Los Olivos',   distrito: 'Los Olivos', cupos: 2,  total: 10, nivel: 'principiante', estado: 'disponible' },
  { id: 7, deporte: 'voley',   titulo: 'Vóley mixto en Surco',          dia: 'viernes',   num: 29, hora: '18:00', lugar: 'Polideportivo Surco',   distrito: 'Surco',      cupos: 4,  total: 12, nivel: 'principiante', estado: 'disponible' },
  { id: 8, deporte: 'basquet', titulo: 'Básquet 3x3 en Barranco',       dia: 'sabado',    num: 30, hora: '11:00', lugar: 'Losa deportiva Barranco', distrito: 'Barranco', cupos: 2,  total: 6,  nivel: 'intermedio',   estado: 'disponible' },
  { id: 9, deporte: 'running', titulo: 'Running nocturno en Miraflores', dia: 'viernes',  num: 29, hora: '21:00', lugar: 'Malecón de Miraflores', distrito: 'Miraflores', cupos: 13, total: 25, nivel: 'libre',        estado: 'disponible' }
];
l
const PROXIMAS = [1, 3, 5];

const TEXTS = {
  es: {
    page_title: 'Sport Match | Find your game',
    skip: 'Saltar al contenido', menu_label: 'Abrir menú', lang_label: 'Idioma',
    nav_home: 'Inicio', nav_search: 'Buscar Partidos', nav_create: 'Crear Evento', nav_how: 'Cómo funciona',
    login: 'Iniciar sesión', register: 'Registrarse',
    hero_title: 'Encuentra tu partido ideal',
    hero_text: 'Descubre actividades deportivas en Lima, conoce jugadores de tu nivel y solicita tu cupo en un solo lugar.',
    search_label: 'Buscar actividades', search_placeholder: 'Buscar por deporte, distrito o recinto deportivo',
    f_sport: 'Deporte', f_district: 'Distrito', f_time: 'Fecha/Hora', f_level: 'Nivel',
    sport_futbol: 'Fútbol', sport_basquet: 'Básquetbol', sport_tenis: 'Tenis', sport_voley: 'Vóley', sport_running: 'Running',
    tm_morning: 'Mañana', tm_afternoon: 'Tarde', tm_evening: 'Noche',
    lvl_principiante: 'Principiante', lvl_intermedio: 'Intermedio', lvl_avanzado: 'Avanzado', lvl_libre: 'Libre',
    btn_search: 'Buscar Partidos', btn_publish: 'Publicar Actividad', adv_filter: 'Filtro Avanzado',
    only_available: 'Mostrar solo actividades con cupos disponibles',
    sec_sports: 'Explora por deporte', sec_near: 'Actividades cerca de ti',
    view_list: 'Lista', view_map: 'Mapa',
    count_n: 'Mostrando {n} actividades', count_one: 'Mostrando 1 actividad',
    no_results: 'No encontramos actividades con esos filtros. Prueba con otros criterios.',
    show_all: 'Ver todas las actividades', show_less: 'Ver menos actividades',
    map_tip: '5 / 14 cupos · Intermedio',
    card_spots: 'Cupos disponibles', card_level: 'Nivel',
    btn_request: 'Solicitar Cupo', btn_detail: 'Ver detalle', btn_view_detail: 'Ver Detalle',
    st_disponible: 'Disponible', st_llenos: 'Cupos Llenos', st_espera: 'En Espera', st_confirmado: 'Confirmado',
    day_lunes: 'Lunes', day_martes: 'Martes', day_miercoles: 'Miércoles', day_jueves: 'Jueves', day_viernes: 'Viernes', day_sabado: 'Sábado', day_domingo: 'Domingo',
    sec_players: 'Para Jugadores', sec_players_sub: 'Encuentra compañeros y actividades a tu medida.',
    p1_t: 'Crea tu perfil deportivo', p1_d: 'Indica tus deportes, nivel y disponibilidad para encontrar actividades compatibles.',
    p2_t: 'Busca y filtra actividades', p2_d: 'Encuentra partidos por deporte, distrito, fecha y horario en segundos.',
    p3_t: 'Solicita tu cupo', p3_d: 'Revisa el detalle, conoce a los participantes y únete al partido.',
    btn_join: 'Unirme al Partido',
    sec_orgs: 'Para Organizadores', sec_orgs_sub: 'Publica tus actividades y completa tus cupos.',
    o1_t: 'Publica tu actividad', o1_d: 'Registra tu partido en tres pasos: deporte, ubicación y cupos.',
    o2_t: 'Controla los cupos', o2_d: 'Consulta participantes y solicitudes pendientes desde Mis Actividades.',
    o3_t: 'Actualiza cuando quieras', o3_d: 'Modifica la información y tus jugadores verán los cambios.',
    sec_panel: 'Actividades Próximas y Perfil Deportivo',
    profile_title: 'Mi Perfil Deportivo', profile_name: 'Tu nombre de usuario', pref_sports: 'Deportes preferidos', pref_level: 'Nivel',
    sec_contact: 'Contáctanos', c_names: 'Nombres', c_surnames: 'Apellidos', c_phone: 'Número de teléfono', c_email: 'Email', c_message: 'Mensaje', c_send: 'Enviar',
    err_required: 'Este campo es obligatorio.', err_email: 'Ingresa un email válido (ejemplo: nombre@correo.com).', err_phone: 'Ingresa un teléfono de 9 dígitos.',
    c_ok: '¡Gracias! Recibimos tu mensaje y te responderemos pronto.',
    footer_tagline: 'Encuentra tu partido. Find your game.',
    f_platform: 'Plataforma', f_help: 'Ayuda', f_lang: 'Idioma',
    f_terms: 'Términos y Condiciones', f_privacy: 'Política de Privacidad', f_contact: 'Contacto',
    f_rights: 'Todos los derechos reservados.', close: 'Cerrar',
    dlg_login_title: 'Iniciar sesión', dlg_login_text: 'El inicio de sesión estará disponible en la siguiente etapa del proyecto.',
    dlg_register_title: 'Crea tu cuenta', dlg_register_text: 'El registro de jugadores y organizadores estará disponible en la siguiente etapa del proyecto.',
    dlg_request_title: 'Inicia sesión para continuar', dlg_request_text: 'Necesitas una cuenta de jugador para solicitar un cupo o ver el detalle de la actividad.',
    dlg_publish_title: 'Solo para organizadores', dlg_publish_text: 'Para publicar una actividad necesitas una cuenta de organizador.'
  },
  en: {
    page_title: 'Sport Match | Find your game',
    skip: 'Skip to content', menu_label: 'Open menu', lang_label: 'Language',
    nav_home: 'Home', nav_search: 'Find Matches', nav_create: 'Create Event', nav_how: 'How it works',
    login: 'Log in', register: 'Sign up',
    hero_title: 'Find your perfect match',
    hero_text: 'Discover sports activities in Lima, meet players at your level and request your spot in one place.',
    search_label: 'Search activities', search_placeholder: 'Search by sport, district or sports venue',
    f_sport: 'Sport', f_district: 'District', f_time: 'Date/Time', f_level: 'Level',
    sport_futbol: 'Soccer', sport_basquet: 'Basketball', sport_tenis: 'Tennis', sport_voley: 'Volleyball', sport_running: 'Running',
    tm_morning: 'Morning', tm_afternoon: 'Afternoon', tm_evening: 'Evening',
    lvl_principiante: 'Beginner', lvl_intermedio: 'Intermediate', lvl_avanzado: 'Advanced', lvl_libre: 'Open',
    btn_search: 'Find Matches', btn_publish: 'Publish Activity', adv_filter: 'Advanced Filter',
    only_available: 'Show only activities with available spots',
    sec_sports: 'Explore by sport', sec_near: 'Activities near you',
    view_list: 'List', view_map: 'Map',
    count_n: 'Showing {n} activities', count_one: 'Showing 1 activity',
    no_results: 'We found no activities with those filters. Try different criteria.',
    show_all: 'See all activities', show_less: 'See fewer activities',
    map_tip: '5 / 14 spots · Intermediate',
    card_spots: 'Available spots', card_level: 'Level',
    btn_request: 'Request Spot', btn_detail: 'View details', btn_view_detail: 'View Details',
    st_disponible: 'Available', st_llenos: 'Full', st_espera: 'Pending', st_confirmado: 'Confirmed',
    day_lunes: 'Monday', day_martes: 'Tuesday', day_miercoles: 'Wednesday', day_jueves: 'Thursday', day_viernes: 'Friday', day_sabado: 'Saturday', day_domingo: 'Sunday',
    sec_players: 'For Players', sec_players_sub: 'Find teammates and activities that fit you.',
    p1_t: 'Create your sports profile', p1_d: 'Tell us your sports, level and availability to find compatible activities.',
    p2_t: 'Search and filter activities', p2_d: 'Find matches by sport, district, date and time in seconds.',
    p3_t: 'Request your spot', p3_d: 'Check the details, meet the participants and join the match.',
    btn_join: 'Join a Match',
    sec_orgs: 'For Organizers', sec_orgs_sub: 'Publish your activities and fill your spots.',
    o1_t: 'Publish your activity', o1_d: 'Register your match in three steps: sport, location and spots.',
    o2_t: 'Control your spots', o2_d: 'Check participants and pending requests from My Activities.',
    o3_t: 'Update anytime', o3_d: 'Edit the information and your players will see the changes.',
    sec_panel: 'Upcoming Activities and Sports Profile',
    profile_title: 'My Sports Profile', profile_name: 'Your username', pref_sports: 'Preferred sports', pref_level: 'Level',
    sec_contact: 'Contact us', c_names: 'First name', c_surnames: 'Last name', c_phone: 'Phone number', c_email: 'Email', c_message: 'Message', c_send: 'Send',
    err_required: 'This field is required.', err_email: 'Enter a valid email (example: name@mail.com).', err_phone: 'Enter a 9-digit phone number.',
    c_ok: 'Thank you! We received your message and will reply soon.',
    footer_tagline: 'Encuentra tu partido. Find your game.',
    f_platform: 'Platform', f_help: 'Help', f_lang: 'Language',
    f_terms: 'Terms and Conditions', f_privacy: 'Privacy Policy', f_contact: 'Contact',
    f_rights: 'All rights reserved.', close: 'Close',
    dlg_login_title: 'Log in', dlg_login_text: 'Login will be available in the next stage of the project.',
    dlg_register_title: 'Create your account', dlg_register_text: 'Player and organizer sign-up will be available in the next stage of the project.',
    dlg_request_title: 'Log in to continue', dlg_request_text: 'You need a player account to request a spot or see the activity details.',
    dlg_publish_title: 'Organizers only', dlg_publish_text: 'To publish an activity you need an organizer account.'
  }
};
